id: pacific.base.ig                                                                  # a unique identifier for this IG - you will need to update ig.ini with
packageId: pacific.base.ig                                                           # the packageId must match the id above
canonical: https://healthinfoservices.net/pacific-base-ig                            # the canonical URL for this IG ideally with a domain you control
version: 1.0.0                                                                       # the version of this IG - update as needed
name: PacificBaseIG                                                                  # computer-readable name without spaces
title: Pacific Base FHIR Implementation Guide                                             # title of the IG
description: FHIR Implementation Guide with Base Definitions for nations in the Pacific   # this will show as the description of the IG
status: draft # draft | active | retired | unknown

# update these as required
copyrightYear: 2026
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: MIT

# this is where you can change the menu structure of the IG
menu:
  Home: index.html
  Artifacts: artifacts.html

# leave these settings as is unless you know what you're doing and have a reason to change them
fhirVersion: 4.3.0
instanceOptions:
  manualSliceOrdering: true
